version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: slurm-mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  postgres:
    image: postgres:14.5
    hostname: postgres
    container_name: slurm-postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "yes"
      POSTGRES_DB: "rstudio"
    volumes:
      - var_lib_postgres:/var/lib/postgres
    expose:
      - "5432"

  slurmdbd:
    image: slurm-docker-cluster:${RSWB_VERSION:-2022.07.2-576.pro12}-slurm-${SLURM_VERSION:-22.05.4-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile 
      args:
        SLURM_VERSION: ${SLURM_VERSION:-22.05.4-1}
        RSWB_VERSION: ${RSWB_VERSION:-2022.07.2-576.pro12}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
    command: ["slurmdbd"]
    container_name: slurm-slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${RSWB_VERSION:-2022.07.2-576.pro12}-slurm-${SLURM_VERSION:-22.05.4-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile
      args:
        SLURM_VERSION: ${SLURM_VERSION:-22.05.4-1}
        RSWB_VERSION: ${RSWB_VERSION:-2022.07.2-576.pro12}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
    command: ["slurmctld"]
    container_name: slurm-slurmctld
    hostname: slurmctld
    privileged: true 
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - home:/home
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  rstudio1:
    image: slurm-docker-cluster:${RSWB_VERSION:-2022.07.2-576.pro12}-slurm-${SLURM_VERSION:-22.05.4-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile
      args:
        SLURM_VERSION: ${SLURM_VERSION:-22.05.4-1}
        RSWB_VERSION: ${RSWB_VERSION:-2022.07.2-576.pro12}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
    command: ["rstudio"]
    container_name: slurm-rstudio1
    hostname: rstudio1
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - var_lib_rstudio_server:/var/lib/rstudio-server
      - home:/home
      - ./singularity/containers:/opt/apptainer/containers    
    expose:
      - "8787"
    ports:
      - "8788:8787"
    depends_on:
      - "slurmctld"
      - "postgres"
    environment:
      RSP_LICENSE: ${RSP_LICENSE}


  rstudio2:
    image: slurm-docker-cluster:${RSWB_VERSION:-2022.07.2-576.pro12}-slurm-${SLURM_VERSION:-22.05.4-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile
      args:
        SLURM_VERSION: ${SLURM_VERSION:-22.05.4-1}
        RSWB_VERSION: ${RSWB_VERSION:-2022.07.2-576.pro12}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
    command: ["rstudio"]
    container_name: slurm-rstudio2
    hostname: rstudio2
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - var_lib_rstudio_server:/var/lib/rstudio-server
      - home:/home
      - ./singularity/containers:/opt/apptainer/containers
    expose:
      - "8787"
    ports:
      - "8789:8787"
    depends_on:
      - "slurmctld"
      - "postgres"
    environment:
      RSP_LICENSE: ${RSP_LICENSE}

  c1:
    image: slurm-docker-cluster:${RSWB_VERSION:-2022.07.2-576.pro12}-slurm-${SLURM_VERSION:-22.05.4-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile
      args:
        SLURM_VERSION: ${SLURM_VERSION:-22.05.4-1}
        RSWB_VERSION: ${RSWB_VERSION:-2022.07.2-576.pro12}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
    command: ["slurmd"]
    hostname: c1
    container_name: slurm-c1
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - var_lib_rstudio_server:/var/lib/rstudio-server
      - home:/home
      - ./singularity/containers:/opt/apptainer/containers
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:${RSWB_VERSION:-2022.07.2-576.pro12}-slurm-${SLURM_VERSION:-22.05.4-1}-${DIST:-jammy}
    build:
      context: .
      dockerfile: Dockerfile.compile
      args:
        SLURM_VERSION: ${SLURM_VERSION:-22.05.4-1}
        RSWB_VERSION: ${RSWB_VERSION:-2022.07.2-576.pro12}
        DIST: ${DIST:-jammy}
        DISTNUM: ${DISTNUM:-2204}
    command: ["slurmd"]
    hostname: c2
    container_name: slurm-c2
    privileged: true
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - var_lib_rstudio_server:/var/lib/rstudio-server
      - home:/home
      - ./singularity/containers:/opt/apptainer/containers
    expose:
      - "6818"
    depends_on:
      - "slurmctld"


volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_lib_postgres:
  var_log_slurm:
  home:
  var_lib_rstudio_server:
